### Performing EDA on OLIST Dataset

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snb

In [81]:
customer_data = pd.read_csv("..\data\olist_customers_dataset.csv")
olist_orders = pd.read_csv("..\data\olist_orders_dataset.csv")
olist_order_items = pd.read_csv("..\data\olist_order_items_dataset.csv")
olist_order_payments = pd.read_csv("..\data\olist_order_payments_dataset.csv")
olist_order_reviews = pd.read_csv("..\data\olist_order_reviews_dataset.csv")
olist_products = pd.read_csv("..\data\olist_products_dataset.csv")
olist_product_category = pd.read_csv("..\data\product_category_name_translation.csv")

In [110]:
customer_data.head()
olist_orders.head()
olist_order_items.head()
# olist_order_payments.head()
# # olist_order_reviews.head()
# olist_products.head()
# olist_product_category.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

### Checking Multiple Payments issue

In [ ]:

counts = olist_order_payments["order_id"].value_counts()
duplicate_ids = counts[counts>1].index
olist_order_payments[olist_order_payments["order_id"].isin(duplicate_ids)].sort_values(by="order_id")

#Faster Way
olist_order_payments[olist_order_payments.duplicated(subset=['order_id'], keep=False)].sort_values(by='order_id')

In [ ]:
# Grouping multiple orders in payments
unique_order_payments = olist_order_payments.groupby(["order_id"]).agg(max_installments=('payment_installments', 'max'),
                                                                       max_methods = ('payment_sequential', 'max'),
                                                                       total_payment = ('payment_value','sum')).reset_index()
primary_payments=olist_order_payments.sort_values(by="payment_value", ascending=False).drop_duplicates(subset="order_id")
primary_payments

# Final Cleaned Payments Data
olist_cleaned_payments = pd.merge(primary_payments[['order_id','payment_type']], unique_order_payments,
                                  on="order_id", how="inner")
olist_cleaned_payments.head(26)

### Merging customer and order data

In [ ]:

customer_order_data = pd.merge(customer_data, olist_orders, how="left", on="customer_id")
customer_order_data.head()

#### pd.merge ignores Index!!

In [108]:
# Merging Customer and Payment data
master_customer_data = pd.merge(customer_order_data, olist_cleaned_payments, on="order_id", how="inner")
master_customer_data.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_type,max_installments,max_methods,total_payment
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,credit_card,2,1,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,credit_card,8,1,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,credit_card,7,1,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,credit_card,1,1,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,credit_card,8,1,252.25

### order_items and product data handling

In [125]:
olist_order_items[olist_order_items.duplicated(subset=["order_id"],keep=False)]
olist_order_items.groupby(["order_id","product_id"]).agg(num_orders=("order_item_id","max")).head(50)

                                                                   num_orders
order_id                         product_id
00010242fe8c5a6d1ba2dd792cb16214 4244733e06e7ecb4970a6e2683c13e61           1
00018f77f2f0320c557190d7a144bdd3 e5f2d52b802189ee658865ca93d83a8f           1
000229ec398224ef6ca0657da4fc703e c777355d18b72b67abbeef9df44fd0fd           1
00024acbcdf0a6daa1e931b038114c75 7634da152a4610f1595efa32f14722fc           1
00042b26cf59d7ce69dfabb4e55b4fd9 ac6c3623068f30de03045865e4e10089           1
00048cc3ae777c65dbb7d2a0634bc1ea ef92defde845ab8450f9d70c526ef70f           1
00054e8431b9d7675808bcb819fb4a32 8d4f2bb7e93e6710a28f34fa83ee7d28           1
000576fe39319847cbb9d288c5617fa6 557d850972a7d6f792fd18ae1400d9b6           1
0005a1a1728c9d785b8e2b08b904576c 310ae3c140ff94b03219ad0adc3c778f           1
0005f50442cb953dcd1d21e1fb923495 4535b0e1091c278dfd193e5a1d63b39f           1
00061f2a7bc09da83e415a52dc8a4af1 d63c1011f49d98b976c352955b1c4bea           1
00063b381e2406b52ad429470734ebd5 f177554ea93259a5b282f24e33f65ab6           1
0006ec9db01a64e59a68b2c340bf65a7 99a4788cb24856965c36a24e339b6058           1
0008288aa423d2a3f00fcb17cd7d8719 368c6c730842d78016ad823897a372db           2
0009792311464db532ff765bf7b182ae 8cab8abac59158715e0d70a36c807415           1
0009c9a17f916a706d71784483a5d643 3f27ac8e699df3d300ec4a5d8c5cf0b2           1
000aed2e25dbad2f9ddb70584c5a2ded 4fa33915031a8cde03dd0d3e8fb27f01           1
000c3e6612759851cc3cbb4b83257986 b50c950aba0dcead2c48032a690ce817           1
000e562887b1f2006d75e0be9558292e 5ed9eaf534f6936b51d0b6c5e4d5c2e9           1
000e63d38ae8c00bbcb5a30573b99628 553e0e7590d3116a072507a3635d2877           1
000e906b789b55f64edcb1f84030f90d 57d79905de06d8897872c551bfd09358           1
000f25f4d72195062c040b12dce9a18a 1c05e0964302b6cf68ca0d15f326c6ba           1
001021efaa8636c29475e7734483457d 5d7c23067ed3fc8c6e699b9373d5890b           1
0010b2e5201cc5f1ae7e9c6cc8f5bd00 5a419dbf24a8c9718fe522b81c69f61a           1
00119ff934e539cf26f92b9ef0cdfed8 21b1c2f67a9aafb5af0eb06c13b9dbda           1
0011d82c4b53e22e84023405fb467e57 c389f712c4b4510bc997cee93e8b1a28           1
00125cb692d04887809806618a2a145f 1c0c0093a48f13ba70d0c6b0a9157cb7           1
00130c0eee84a3d909e75bc08c5c3ca1 89321f94e35fc6d7903d36f74e351d40           1
0013503b13da1eac686219390b7d641b 38afdf723b95d455b418a0f57d623c6b           1
00137e170939bba5a3134e2386413108 672e757f331900b9deea127a2a7b79fd           1
001427c0ec99cf8af737bd88e92fd444 28b4eced95a52d9c437a4caf9d311b95           1
00143d0f86d6fbd9f9b38ab440ac16f5 e95ee6822b66ac6058e2e4aff656071a           3
0014ae671de39511f7575066200733b7 23365beed316535b4105bd800c46670e           1
0015ebb40fb17286bea51d4607c4733c 50fd2b788dc166edd20512370dac54df           1
00169e31ef4b29deaae414f9a5e95929 b10eba910a974df70b8a12d0665cdb9e           1
0016dfedd97fc2950e388d2971d718c7 4089861a1bd4685da70bddd6b4f974f1           1
0017afd5076e074a48f1f1a4c7bac9c5 fe59a1e006df3ac42bf0ceb876d70969           1
001862358bf858722e1e2ae000cfed8b c6dd917a0be2a704582055949915ab32           1
0019c29108428acffd089c36103c9440 28b4eced95a52d9c437a4caf9d311b95           1
001ab0a7578dd66cd4b0a71f5b6e1e41 0b0172eb0fd18479d29c3bc122c058c2           3
001ac194d4a326a6fa99b581e9a3d963 dbaee28f4ee64465838a229582d77520           1
001b76dd48a5b1eee3e87778daa40df8 dbb67791e405873b259e4656bf971246           1
001c85b5f68d2be0cb0797afc9e8ce9a 84f456958365164420cfc80fbe4c7fab           1
001d8f0e34a38c37f7dba2a37d4eba8b e67307ff0f15ade43fcb6e670be7a74c           2
001daeb0eddc45b999bad0801ad9d273 30c01cc81c9eb80469371743813789cc           1
001dbc16dc51075e987543d23a0507c7 777d2e438a1b645f3aec9bd57e92672c           1
001e7ba991be1b19605ca0316e7130f9 884fa3cd42986ba480ea2f8ae4e25ff7           1
001e7cf2ad6bef3ade12ebc56ceaf0f3 bdcf6a834e8faa30dac3886c7a58e92e           1
0020262c8a370bd5a174ea6a2a267321 a5341e3f8155dbb3e62323d3ea289729           1
0020a222f55eb79a372d0efee3cca688 e19ddcc85537b41f22116c8d5425ef46           1